import { ShepherdAsset } from "@/types/domain";

export const demoScreenshotAssets: ShepherdAsset[] = [
  {
    id: "demo-flight",
    deviceAssetId: "demo-flight",
    uri: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=900&auto=format&fit=crop",
    filename: "flight-confirmation-chicago-los-angeles.png",
    width: 1170,
    height: 2532,
    fileSize: 1_400_000,
    capturedAt: new Date().toISOString(),
    category: "travel",
    summary: "Flight confirmation for a Chicago to Los Angeles trip.",
    reason: "Useful travel details should be archived instead of left loose in the camera roll.",
    suggestedAction: "archive",
    isSensitive: false,
    status: "active"
  },
  {
    id: "demo-recipe",
    deviceAssetId: "demo-recipe",
    uri: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=900&auto=format&fit=crop",
    filename: "pizza-recipe-screenshot.png",
    width: 1170,
    height: 2532,
    fileSize: 1_100_000,
    capturedAt: new Date().toISOString(),
    category: "recipe",
    summary: "Pizza recipe screenshot with ingredients and oven timing.",
    reason: "Recipe screenshots are worth saving to a category so they can be found later.",
    suggestedAction: "save_category",
    isSensitive: false,
    status: "active"
  },
  {
    id: "demo-receipt",
    deviceAssetId: "demo-receipt",
    uri: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=900&auto=format&fit=crop",
    filename: "hardware-store-receipt.png",
    width: 1170,
    height: 2532,
    fileSize: 900_000,
    capturedAt: new Date().toISOString(),
    category: "receipt",
    summary: "Receipt screenshot for a hardware store purchase.",
    reason: "Financial records should be reviewed before deleting.",
    suggestedAction: "review_sensitive",
    isSensitive: true,
    status: "active"
  },
  {
    id: "demo-shopping",
    deviceAssetId: "demo-shopping",
    uri: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=900&auto=format&fit=crop",
    filename: "toyota-quote-shopping-screenshot.png",
    width: 1170,
    height: 2532,
    fileSize: 1_250_000,
    capturedAt: new Date().toISOString(),
    category: "shopping",
    summary: "Toyota quote and shopping comparison screenshot.",
    reason: "Quote screenshots are useful for search and should be archived.",
    suggestedAction: "archive",
    isSensitive: false,
    status: "active"
  },
  {
    id: "demo-password",
    deviceAssetId: "demo-password",
    uri: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=900&auto=format&fit=crop",
    filename: "password-login-screenshot.png",
    width: 1170,
    height: 2532,
    fileSize: 800_000,
    capturedAt: new Date().toISOString(),
    category: "password",
    summary: "Possible login or credential screenshot.",
    reason: "This may include credential information. Review privately and avoid storing it long term.",
    suggestedAction: "review_sensitive",
    isSensitive: true,
    status: "active"
  },
  {
    id: "demo-note",
    deviceAssetId: "demo-note",
    uri: "https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=900&auto=format&fit=crop",
    filename: "daughter-birthday-note.png",
    width: 1170,
    height: 2532,
    fileSize: 700_000,
    capturedAt: new Date().toISOString(),
    category: "note",
    summary: "Birthday planning note screenshot.",
    reason: "Personal notes are useful for search and should be saved to a category.",
    suggestedAction: "save_category",
    isSensitive: false,
    status: "active"
  }
];
